ci: 增加编译后的jar包有效性测试，预防编译失败的低级问题

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -69,6 +69,16 @@ jobs:
         chmod +x package.sh
         ./package.sh
 
+    - name: Test Jar
+      run: |
+        version=`java -Dfile.encoding=utf-8 -jar INeedBiliAV.jar -v 2>&1 | tail -n 1`
+        if [ "$version" != "v${{steps.tag_latest.outputs.value}}" ]  ; then
+          echo $version
+          echo "v${{steps.tag_latest.outputs.value}}"
+          echo '::warning:: Query version of INeedBiliAV.jar failed...'
+          exit 1
+        fi
+
     - name: ZIP files
       run: |
         rm -rf ./config
